# Generated by Django 3.2.12 on 2022-04-17 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ингредиента')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('packing', models.FloatField(verbose_name='Фасовка')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.measurement')),
            ],
        ),
    ]
