# Generated by Django 3.2.12 on 2022-05-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20220503_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientConsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.ingredient')),
            ],
            options={
                'ordering': ['-ingredient__name'],
            },
        ),
    ]
