# Generated by Django 3.2.12 on 2022-05-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipelayer'),
        ('ingredients', '0003_ingredientconsistency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientconsistency',
            options={'ordering': ['ingredient__name']},
        ),
        migrations.AddField(
            model_name='ingredientconsistency',
            name='recipe_layer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_consistency', to='recipes.recipelayer'),
            preserve_default=False,
        ),
    ]
