# Generated by Django 3.2.12 on 2022-04-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_confectioner',
            field=models.BooleanField(default=False, verbose_name='Статус кондитера'),
        ),
    ]
