# Generated by Django 3.2.12 on 2022-04-10 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import funcake.recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('preview', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст рецепта')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', funcake.recipes.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения')),
                ('is_visible', models.BooleanField(default=False, verbose_name='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
