# Generated by Django 3.2.12 on 2022-04-10 14:48

from django.db import migrations, models
import funcake.recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img_prew',
            field=models.ImageField(blank=True, upload_to=funcake.recipes.models.recipe_directory_path, verbose_name='Фото превью'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
    ]
