# Generated by Django 3.2.12 on 2022-05-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220410_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название слоя')),
                ('diameter', models.FloatField(verbose_name='Диаметр слоя')),
                ('is_template', models.BooleanField(default=False, verbose_name='Шаблонный слой')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='recipes.recipe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
